[platformio]
src_dir = main
data_dir = data/power-analyzer

[env:esp32_d0wd_psram]
platform      = espressif32 @ 6.10.0
framework     = espidf
board         = esp-wrover-kit      ; PSRAM-fähiges Profil
monitor_speed = 115200

; Flash & PSRAM
board_build.flash_size = 4MB
board_build.psram_size = 8192       ; 8 MB
board_build.extra_flags = -DBOARD_HAS_PSRAM

; Deine bisherigen Flags
build_flags =
    -Wno-cpp
build_unflags = -DESP_DSP_USE_ASM
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
